export const ON_CHANGE_USERNAME = 'ON_CHANGE_USERNAME'
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_NAME = 'SET_NAME'
export const SET_ID = 'SET_ID'
export const UPDATE_MSG = 'UPDATE_MSG'
export const SET_SEX = 'SET_SEX'
