export const ON_CHANGE_USERNAME = 'ON_CHANGE_USERNAME'
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD'
export const SET_TOKEN = 'SET_TOKEN'
// export const LOGIN = 'LOGIN'
// export const LOGIN_ASYNC = 'LOGIN_ASYNC'
