export const ANSWER_SELECT_OPTION = 'ANSWER_SELECT_OPTION'
export const ANSWER_SET_QUESTIONS = 'ANSWER_SET_QUESTIONS'
export const POST_ANSWER = 'POST_ANSWER'
export const CHECK_EVER_ANSWER = 'CHECK_EVER_ANSWER'
